//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlPrime.Tasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlPrime.Tasks.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding serialization parameter &apos;{0}&apos; with value &apos;{1}&apos;.
        /// </summary>
        internal static string AddingSerializationParameter {
            get {
                return ResourceManager.GetString("AddingSerializationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create result document {0}.  Result document URIs must use the &apos;file&apos; URI scheme.
        /// </summary>
        internal static string CannotCreateResultDocument {
            get {
                return ResourceManager.GetString("CannotCreateResultDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating result document {0}.
        /// </summary>
        internal static string CreateResultDocument {
            get {
                return ResourceManager.GetString("CreateResultDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discarding primary result document {0}.
        /// </summary>
        internal static string DiscardingPrimaryResultDocument {
            get {
                return ResourceManager.GetString("DiscardingPrimaryResultDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setting {0} as context item.
        /// </summary>
        internal static string SettingContextItem {
            get {
                return ResourceManager.GetString("SettingContextItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading serialization parameters from {0}.
        /// </summary>
        internal static string SettingSerializationParameter {
            get {
                return ResourceManager.GetString("SettingSerializationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation type {0} not recognised.  Should be &apos;dtd&apos;, &apos;schema&apos; or &apos;none&apos;..
        /// </summary>
        internal static string UnknownValidationType {
            get {
                return ResourceManager.GetString("UnknownValidationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization parameter &apos;{0}&apos; is unrecognised.
        /// </summary>
        internal static string UnrecognisedSerializationParameter {
            get {
                return ResourceManager.GetString("UnrecognisedSerializationParameter", resourceCulture);
            }
        }
    }
}
